#!/usr/bin/env python2.7

import sys
import os
#os.chdir(os.path.dirname(__file__))

import sandcrawler.scraper.testrig as testrig

# Scrapers import from 'scraper'
sys.path.append('sandcrawler')

testrig.test_script_main()
